### ISSUE TITLE
Incorrect grading system

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/crypto-class#11]
- We do not require a minimum grade in the written exam
- The required minimum final grade is 5, not 4.5
- The `_|` characters are the floor characters. UTF8 should be used accordingly.

**Comment by kioplato** [comment]
Already made PR. Waiting for review & merge. https://github.com/dionyziz/crypto-class/pull/14

**Comment by kkanellis** [comment]
#14 Closed.
