### ISSUE TITLE
Διόρθωση πλατφόρμας θεωρητικών ασκήσεων

### ISSUE THREAD

**Issue by zetavar** [dionyziz/crypto-class#39]
Για να διευκολυνθει η διαδικασία της διόρθωσης των θεωρητικών ασκήσεων χρειάζονται κάποιες αλλαγές:
1. Να μπορούμε να επιλέξουμε χωριστά κάθε σειρά ασκήσεων
2. Να μπορούμε να κατεβάσουμε και να εκτυπώσουμε μαζικά τις επιλεγμένες ασκήσεις

**Comment by kkanellis** [comment]
#43
