### ISSUE TITLE
Must not require ID number for AYLO/MPLA

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/crypto-class#6]
New students of MPLA/AYLO do not yet have ID numbers. They should be able to register by selecting their school and leaving their number empty for now.

This must be done soon because they need to solve the exercises for lecture 1.

**Comment by abresas** [comment]
AYLO?

**Comment by dionyziz** [comment]
AYLO = MPLA

**Comment by dionyziz** [comment]
Resolved by [asking students](https://shmmy.ntua.gr/forum/viewtopic.php?p=840170#p840170) to register with ID = "-".
